services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:7.3.3
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      # KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0   # no delay before rebalance
      # KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: 1000    # allow small timeouts
      # KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 30000   # max 30s

  kafka-ui:
    container_name: kafka-ui
    image: kafbat/kafka-ui:latest
    network_mode: host
    # ports:
    #   - 8080:8080
    depends_on:
      - kafka
      - zookeeper
    environment:
      SERVER_PORT: 8020
      DYNAMIC_CONFIG_ENABLED: 'true'

      # --- Kafka Cluster Config ---
      KAFKA_CLUSTERS_0_NAME: Localhost
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: localhost:29092

      # --- Enable JSON Value SerDe ---
      KAFKA_CLUSTERS_0_SERDE_VALUE: json
      KAFKA_CLUSTERS_0_SERDE_VALUE_JSON_CLASS: java.lang.String

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    depends_on:
      - kafka
      - zookeeper
    network_mode: host
    ports:
      - "8021:8080"
    environment:
      KAFKA_BROKERS: "localhost:29092"
      CONSOLE_UI_THEME: dark

